'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  FileText, 
  Sparkles, 
  Download, 
  CheckCircle,
  Clock,
  FileCheck
} from 'lucide-react';
import { cn } from '@/lib/utils';

export default function PolicyGeneratorPage() {
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState<string>('');
  const [displayedContent, setDisplayedContent] = useState<string>('');

  const templates = [
    {
      id: 'operational_efficiency',
      name: 'Operational Efficiency Report',
      description: 'VRP results, cost analysis, and recommendations',
      icon: FileCheck,
      color: '#00f5ff',
    },
    {
      id: 'risk_assessment',
      name: 'Risk Assessment Report',
      description: 'Fleet risk analysis with mitigation strategies',
      icon: FileText,
      color: '#ef4444',
    },
    {
      id: 'fairness_audit',
      name: 'Fairness Audit Report',
      description: 'Bias detection and equity analysis',
      icon: FileText,
      color: '#39ff14',
    },
    {
      id: 'ethical_compliance',
      name: 'Ethical Compliance Report',
      description: 'Ethical framework compliance assessment',
      icon: FileText,
      color: '#a855f7',
    },
  ];

  const handleGenerate = async () => {
    setIsGenerating(true);
    setDisplayedContent('');
    
    // Simulate AI generation
    await new Promise(r => setTimeout(r, 1000));
    
    const content = `# ${templates.find(t => t.id === selectedTemplate)?.name}

## Executive Summary

This report provides a comprehensive analysis of our logistics operations for the period of January 2026. Key findings indicate significant opportunities for optimization while maintaining our commitment to ethical operations and stakeholder satisfaction.

## Key Findings

### Operational Performance
- **Route Efficiency**: 18% improvement achieved through AI-driven VRP optimization
- **On-Time Delivery Rate**: 94.2% (exceeds 90% target)
- **Fleet Utilization**: 87% average capacity utilization

### Risk Assessment
- Overall fleet risk score: 0.28 (LOW)
- No critical safety incidents reported
- Weather-related delays: 3.2% of total deliveries

### Fairness Metrics
- Geographic equity score: 0.86
- Driver workload Gini coefficient: 0.24 (fair distribution)
- Demographic parity achieved across all customer segments

## Recommendations

1. **Increase Al Quoz Zone Coverage**: Deploy additional resources during peak hours
2. **Implement Predictive Maintenance**: Reduce vehicle downtime by 15%
3. **Enhance Driver Training**: Focus on fatigue management protocols
4. **Expand AI Communication**: Increase automated customer notifications

## Compliance Status

| Regulation | Status | Score |
|------------|--------|-------|
| DOT Requirements | ✅ Compliant | 95% |
| Labor Laws | ✅ Compliant | 92% |
| Data Privacy | ✅ Compliant | 98% |
| Environmental | ⚠️ Review | 85% |

## Next Steps

- Schedule quarterly fairness audits
- Continue monitoring risk indicators
- Prepare stakeholder engagement plan
- Review environmental compliance measures

---
*Generated by Logistics AI Platform | Powered by Gemini*
*Report Date: January 2026*`;

    setGeneratedContent(content);
    
    // Typing animation
    for (let i = 0; i <= content.length; i++) {
      await new Promise(r => setTimeout(r, 5));
      setDisplayedContent(content.slice(0, i));
    }
    
    setIsGenerating(false);
  };

  return (
    <div className="min-h-screen bg-dark-900 p-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-8"
      >
        <h1 className="text-3xl font-bold text-white mb-2">
          Policy Brief <span className="text-accent-magenta">Generator</span>
        </h1>
        <p className="text-gray-400">
          AI-powered document synthesis with Gemini
        </p>
      </motion.div>

      <div className="grid grid-cols-12 gap-6">
        {/* Template Selection */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="col-span-4"
        >
          <div className="glass-dark rounded-2xl p-6">
            <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <FileText className="w-5 h-5 text-accent-magenta" />
              Templates
            </h3>
            
            <div className="space-y-3">
              {templates.map((template) => {
                const Icon = template.icon;
                return (
                  <motion.button
                    key={template.id}
                    whileHover={{ scale: 1.02 }}
                    onClick={() => setSelectedTemplate(template.id)}
                    className={cn(
                      'w-full p-4 rounded-xl text-left transition-all',
                      selectedTemplate === template.id
                        ? 'bg-accent-magenta/20 border border-accent-magenta'
                        : 'bg-dark-700 border border-transparent hover:bg-dark-600'
                    )}
                  >
                    <div className="flex items-center gap-3">
                      <div
                        className="w-10 h-10 rounded-lg flex items-center justify-center"
                        style={{ backgroundColor: `${template.color}20` }}
                      >
                        <Icon className="w-5 h-5" style={{ color: template.color }} />
                      </div>
                      <div>
                        <p className="font-medium text-white">{template.name}</p>
                        <p className="text-xs text-gray-400">{template.description}</p>
                      </div>
                    </div>
                  </motion.button>
                );
              })}
            </div>

            {selectedTemplate && (
              <motion.button
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleGenerate}
                disabled={isGenerating}
                className={cn(
                  'w-full mt-6 py-4 rounded-xl font-medium flex items-center justify-center gap-2',
                  isGenerating
                    ? 'bg-dark-600 text-gray-400'
                    : 'bg-gradient-to-r from-accent-magenta to-accent-purple text-white'
                )}
              >
                {isGenerating ? (
                  <>
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
                    >
                      <Sparkles className="w-5 h-5" />
                    </motion.div>
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    Generate Document
                  </>
                )}
              </motion.button>
            )}
          </div>

          {/* Recent Documents */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.1 }}
            className="glass-dark rounded-2xl p-6 mt-6"
          >
            <h3 className="text-lg font-semibold text-white mb-4">Recent Documents</h3>
            <div className="space-y-2">
              {[
                { name: 'Weekly Ops Report', time: '2 hours ago' },
                { name: 'Risk Assessment Q1', time: '1 day ago' },
                { name: 'Fairness Audit Dec', time: '3 days ago' },
              ].map((doc, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between p-3 bg-dark-700 rounded-lg"
                >
                  <div className="flex items-center gap-3">
                    <CheckCircle className="w-4 h-4 text-green-400" />
                    <span className="text-sm text-white">{doc.name}</span>
                  </div>
                  <span className="text-xs text-gray-400">{doc.time}</span>
                </div>
              ))}
            </div>
          </motion.div>
        </motion.div>

        {/* Document Preview */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          className="col-span-8"
        >
          <div className="glass-dark rounded-2xl p-6 h-full">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-white">Document Preview</h3>
              {generatedContent && (
                <motion.button
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="flex items-center gap-2 px-4 py-2 bg-dark-700 rounded-lg text-gray-400 hover:text-white transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Export PDF
                </motion.button>
              )}
            </div>
            
            <div className="bg-dark-800 rounded-xl p-6 h-[calc(100vh-300px)] overflow-y-auto">
              {displayedContent ? (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="prose prose-invert prose-sm max-w-none"
                >
                  <pre className="whitespace-pre-wrap font-sans text-gray-300 leading-relaxed">
                    {displayedContent}
                    {isGenerating && (
                      <motion.span
                        animate={{ opacity: [1, 0] }}
                        transition={{ duration: 0.5, repeat: Infinity }}
                        className="inline-block w-2 h-4 bg-accent-magenta ml-1"
                      />
                    )}
                  </pre>
                </motion.div>
              ) : (
                <div className="h-full flex flex-col items-center justify-center text-gray-500">
                  <FileText className="w-16 h-16 mb-4 opacity-50" />
                  <p>Select a template and generate a document</p>
                </div>
              )}
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
